# Generated by Django 4.2.11 on 2026-01-31 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Logdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'This username is already registered'}, max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('utype', models.CharField(default='user', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UnknownFaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='Users/')),
                ('dob', models.DateField()),
                ('kin', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('username', models.CharField(error_messages={'unique': 'This username is already registered.'}, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('reminder', models.TextField()),
                ('time', models.TimeField()),
                ('status', models.SmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SereneMindApp.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='Doctors/')),
                ('dob', models.DateField()),
                ('specialization', models.CharField(max_length=100)),
                ('license', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('logdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='SereneMindApp.logdata')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('dose', models.CharField(max_length=20)),
                ('status', models.SmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SereneMindApp.userdetails')),
            ],
            options={
                'unique_together': {('medicine', 'time', 'dose', 'user')},
            },
        ),
    ]
