# Generated by Django 4.2.11 on 2026-01-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='specialization',
        ),
        migrations.AddField(
            model_name='doctors',
            name='experiance',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
