# Generated by Django 4.2.11 on 2026-01-31 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0002_remove_doctors_specialization_doctors_experiance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='experiance',
            new_name='experience',
        ),
    ]
