# Generated by Django 4.2.11 on 2026-01-31 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0003_rename_experiance_doctors_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='contact',
            new_name='phone',
        ),
    ]
