# Generated by Django 4.2.11 on 2026-01-31 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0004_rename_contact_doctors_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='username',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='logdata',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='SereneMindApp.logdata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctors',
            name='logdata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='SereneMindApp.logdata'),
        ),
    ]
