# Generated by Django 4.2.11 on 2026-01-31 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0005_remove_userdetails_username_userdetails_logdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SereneMindApp.logdata'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SereneMindApp.logdata'),
        ),
    ]
