# Generated by Django 4.2.11 on 2026-01-31 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0006_alter_medicine_user_alter_reminder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='kin',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kin', to='SereneMindApp.logdata'),
            preserve_default=False,
        ),
    ]
