# Generated by Django 4.2.11 on 2026-01-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0007_kin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kin',
            name='description',
        ),
        migrations.AddField(
            model_name='kin',
            name='relation',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
