# Generated by Django 4.2.11 on 2026-01-31 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0008_remove_kin_description_kin_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveSmallIntegerField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('blood_group', models.CharField(max_length=10)),
                ('blood_pressure', models.CharField(max_length=20)),
                ('heart_rate', models.PositiveSmallIntegerField()),
                ('temperature', models.PositiveSmallIntegerField()),
                ('previous_medicine', models.JSONField()),
                ('medicalHistory', models.FileField(upload_to='MedicalHistory/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_details', to='SereneMindApp.logdata')),
            ],
        ),
    ]
