# Generated by Django 4.2.11 on 2026-01-31 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0009_medicaldetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaldetails',
            old_name='medicalHistory',
            new_name='medical_history',
        ),
        migrations.AddField(
            model_name='medicaldetails',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SereneMindApp.doctors'),
            preserve_default=False,
        ),
    ]
