# Generated by Django 4.2.11 on 2026-01-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0010_rename_medicalhistory_medicaldetails_medical_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetails',
            name='height',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicaldetails',
            name='temperature',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
