# Generated by Django 4.2.11 on 2026-02-03 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0011_alter_medicaldetails_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_details', to='SereneMindApp.logdata', unique=True),
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('status', models.SmallIntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SereneMindApp.logdata')),
            ],
        ),
    ]
