# Generated by Django 4.2.11 on 2026-02-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0012_alter_medicaldetails_user_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
