# Generated by Django 4.2.28 on 2026-02-18 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0013_alter_appointments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_details', to='SereneMindApp.logdata'),
        ),
    ]
