# Generated by Django 4.2.11 on 2026-03-09 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0015_alter_medicaldetails_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('status', models.SmallIntegerField(db_comment='0 = not taken, 1 = taken', default=1)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SereneMindApp.medicine')),
            ],
        ),
    ]
