# Generated by Django 4.2.11 on 2026-03-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0016_medicinelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinelog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
