# Generated by Django 4.2.11 on 2026-03-09 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0017_alter_medicinelog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.SmallIntegerField(db_comment='0 = not done, 1 = done', default=1),
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(default=0)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SereneMindApp.reminder')),
            ],
        ),
    ]
