# Generated by Django 4.2.11 on 2026-03-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0018_alter_reminder_status_reminderlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='status',
            field=models.SmallIntegerField(db_comment='0 = not done, 1 = done', default=0),
        ),
    ]
