# Generated by Django 4.2.28 on 2026-03-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0020_alter_reminderlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminderlog',
            name='status',
            field=models.SmallIntegerField(db_comment='0 = not done, 1 = done', default=0),
        ),
    ]
