# Generated by Django 4.2.28 on 2026-03-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SereneMindApp', '0021_alter_reminderlog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reminderlog',
            name='status',
            field=models.SmallIntegerField(db_comment='0 = not done, 1 = done', default=1),
        ),
    ]
